"""empty message

Revision ID: 7510080e2924
Revises: 
Create Date: 2018-08-09 00:37:42.576826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7510080e2924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('aid', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('sensor_data',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('apartment', sa.String(length=64), nullable=False),
    sa.Column('beacon', sa.String(length=64), nullable=True),
    sa.Column('d_01', sa.String(length=64), nullable=True),
    sa.Column('m_01', sa.String(length=64), nullable=True),
    sa.Column('m_02', sa.String(length=64), nullable=True),
    sa.Column('m_03', sa.String(length=64), nullable=True),
    sa.Column('m_04', sa.String(length=64), nullable=True),
    sa.Column('minutes', sa.String(length=64), nullable=True),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['apartment'], ['apartment.aid'], ),
    sa.PrimaryKeyConstraint('datetime', 'apartment')
    )
    op.create_index(op.f('ix_sensor_data_apartment'), 'sensor_data', ['apartment'], unique=False)
    op.create_index(op.f('ix_sensor_data_beacon'), 'sensor_data', ['beacon'], unique=False)
    op.create_index(op.f('ix_sensor_data_d_01'), 'sensor_data', ['d_01'], unique=False)
    op.create_index(op.f('ix_sensor_data_datetime'), 'sensor_data', ['datetime'], unique=False)
    op.create_index(op.f('ix_sensor_data_day'), 'sensor_data', ['day'], unique=False)
    op.create_index(op.f('ix_sensor_data_m_01'), 'sensor_data', ['m_01'], unique=False)
    op.create_index(op.f('ix_sensor_data_m_02'), 'sensor_data', ['m_02'], unique=False)
    op.create_index(op.f('ix_sensor_data_m_03'), 'sensor_data', ['m_03'], unique=False)
    op.create_index(op.f('ix_sensor_data_m_04'), 'sensor_data', ['m_04'], unique=False)
    op.create_index(op.f('ix_sensor_data_minutes'), 'sensor_data', ['minutes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_minutes'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_m_04'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_m_03'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_m_02'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_m_01'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_day'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_datetime'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_d_01'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_beacon'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_apartment'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_table('apartment')
    # ### end Alembic commands ###
